### ISSUE TITLE
Issues getId return null value for gradle project 

### ISSUE THREAD

**Issue by ankur1233** [sridharbandi/Java-a11y#34]
I have setup gradle project and getting Issues.getId() same project run with maven setup it work fine 

**Cannot invoke "io.github.sridharbandi.modal.axe.Issues.getId()" because "issues" is null**
java.lang.NullPointerException: Cannot invoke "io.github.sridharbandi.modal.axe.Issues.getId()" because "issues" is null
	at io.github.sridharbandi.IRunner.lambda$generateHtmlReport$0(IRunner.java:25)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

**Comment by sridharbandi** [comment]
@ankur1233 Can I know the website you are using, I will check it from my side.

**Comment by ankur1233** [comment]
yah sure it's : https://www.hilti.fr/

**Comment by anonymous73612** [comment]
Hello @sridharbandi, we are getting this error _ava.io.FileNotFoundException: ./target/java-a11y/axe/json/f9a05f92-9a3a-4486-a7b5-60ed4db7918d.json (No such file or directory)_ and that's the reason we are getting null pointer on Issues.getId().

But the interesting part is that the json file is correctly generated at this path _testauto/target/java-a11y/axe/json/0c4844d2-e5fb-4be7-9fdf-a196f005547c.json_  but throws an error while reading the json

do you think it's something related to the paths? We would appreciate if you can please take a look at it as it impacts our accessibility testing? 
Thanks in advance!
